security:
    providers:
        jsonRpcProvider:
            id: JsonRpcAuthorizationBundle\Service\DefaultUserProviderService

    firewalls:
        jsonRpc:
            pattern: ^/jsonRpc
            provider: jsonRpcProvider
            guard:
                authenticators:
                    - JsonRpcAuthorizationBundle\Service\AuthenticationService
        default:
            anonymous: ~

    access_control:
        - { path: '^/jsonRpc', roles: ROLE_RPC_USER}
